PreCommit:
  ALL:
    exclude: &default_excludes
      - 'node_modules/**/*'
      - 'android/**/*'
      - 'ios/**/*'
  EsLint:
    enabled: true
    required_executable: 'npm'
    command: ['npm', 'run', 'lint', '--', '-f', 'compact']

  HardTabs:
    enabled: true

  TrailingWhitespace:
    enabled: true

PostCheckout:
  NpmInstall:
    enabled: true

PostMerge:
  NpmInstall:
    enabled: true

PostRewrite:
  NpmInstall:
    enabled: true
