// Categories
export const SELECT_CATEGORY_TAG = 'SELECT_CATEGORY_TAG'

// Favorites
export const REQUEST_FAVORITE_PUBLISHERS = 'REQUEST_FAVORITE_PUBLISHERSD'
export const FAVORITE_PUBLISHERS_RECEIVED = 'FAVORITE_PUBLISHERS_RECEIVED'
export const SELECT_FAVORITE_CATEGORY = 'SELECT_FAVORITE_CATEGORY'

// Modal
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

// Notifications
export const REQUEST_NOTIFICATIONS_TAGS = 'REQUEST_NOTIFICATIONS_TAGS'
export const RECEIVE_NOTIFICATIONS_TAGS = 'RECEIVE_NOTIFICATIONS_TAGS'
export const REQUEST_NOTIFICATIONS_PERMISSIONS = 'REQUEST_NOTIFICATIONS_PERMISSIONS'
export const RECEIVE_NOTIFICATIONS_PERMISSIONS = 'RECEIVE_NOTIFICATIONS_PERMISSIONS'

// Onboarding
export const SHOW_ONBOARDING = 'SHOW_ONBOARDING'
export const REQUEST_ONBOARDING = 'REQUEST_ONBOARDING'

// Publishers
export const SELECT_PUBLISHER_CATEGORY = 'SELECT_PUBLISHER_CATEGORY'

// Routes
export const TRACK_ROUTE = 'TRACK_ROUTE'
export const TRACK_POPULAR_ROUTE = 'TRACK_POPULAR_ROUTE'
export const ROUTE_CHANGED = 'ROUTE_CHANGED'

// Tenant
export const REQUEST_TENANT = 'REQUEST_TENANT'
export const ASSIGN_TENANT = 'ASSIGN_TENANT'
export const TENANT_RECEIVED = 'TENANT_RECEIVED'

// Visited Stories
export const REQUEST_VISITED_STORIES = 'REQUEST_VISITED_STORIES'
export const VISITED_STORIES_RECEIVED = 'VISITED_STORIES_RECEIVED'
