# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mttrs' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mttrs
  pod 'Firebase/Core'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'FBAudienceNetwork'
  pod 'Bolts'
  pod 'ReactNativeFabric', path: '../node_modules/react-native-fabric'
  pod 'React', path: '../node_modules/react-native'
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'ReactNativeFBAds', :path => '../node_modules/react-native-fbads'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  target 'mttrsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
