platform :ios, '9.0'

target 'mttrs' do
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'BatchedBridge'
  ]
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'Firebase/Core', '4.0.0'
  pod 'FBSDKCoreKit', '4.23.0'
  pod 'FBSDKShareKit', '4.23.0'
  pod 'FBSDKLoginKit', '4.23.0'
  pod 'FBAudienceNetwork', '4.23.0'
  pod 'Bolts', '1.8.4'
  pod 'ReactNativeFabric', path: '../node_modules/react-native-fabric'
  pod 'ReactNativeFBAds', path: '../node_modules/react-native-fbads'
  pod 'react-native-splash-screen', path: '../node_modules/react-native-splash-screen'
  pod 'SentryReactNative', path: '../node_modules/react-native-sentry'
  pod 'Sentry', '3.0.7'

  target 'mttrsTests' do
    inherit! :search_paths
  end
end
