# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mttrs' do
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'BatchedBridge'
  ]
  pod 'Yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  # Pods for mttrs
  pod 'Firebase/Core', '4.0.0'
  pod 'FBSDKCoreKit', '4.23.0'
  pod 'FBSDKShareKit', '4.23.0'
  pod 'FBSDKLoginKit', '4.23.0'
  pod 'FBAudienceNetwork', '4.23.0'
  pod 'Bolts', '1.8.4'
  pod 'ReactNativeFabric', path: '../node_modules/react-native-fabric'
  pod 'ReactNativeFBAds', :path => '../node_modules/react-native-fbads'

  target 'mttrsTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
