fastlane_version "1.105.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Submit a new Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    sigh
    increment_build_number(xcodeproj: './ios/mttrs.xcodeproj') # Increment the build number
    gym(scheme: "mttrs", project: './ios/mttrs.xcodeproj') # Build the app
    pilot(skip_submission: true) # Upload the app to TestFlight
  end

  after_all do |lane|
    slack(channel: "deploys", message: "Successfully deployed new mttrs alpha update to TestFlight.")
  end
end

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Submit a new Alpha Build to Play Store"
  lane :alpha do
    gradle(task: 'clean', project_dir: "android/") # Clean the Gradle project
    gradle(task: "assemble", build_type: "Release", project_dir: "android/") # Build the Release APK
    supply(track: "alpha", apk: "android/app/build/outputs/apk/app-release.apk") # Upload the APK to the Play Store (alpha)
  end

  after_all do |lane|
    slack(channel: "deploys", message: "Successfully deployed new mttrs alpha update to the Play Store.")
  end
end
